#!/usr/bin/with-contenv bash

now_sleep () {
  sleep infinity &
  wait $!
}

if [[ -x /scripts/torrent-done.sh ]]
then
  # wait for transmission to start

  while :
  do
    echo "Waiting for transmission to start."
    transmission-remote -l
    if [[ $? -eq 0 ]]
    then
      echo "Setting torrent done script"
      transmission-remote --torrent-done-script /scripts/torrent-done.sh
      now_sleep
    fi
    sleep 1
  done
fi
echo "No torrent done script."

now_sleep