name: Create docker image
on:
  workflow_dispatch:
  repository_dispatch:
    types: [start-build]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Bump version and push tag
      id: version
      uses: hennejg/github-tag-action@v4.3.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Login to Harbor
      uses: docker/login-action@v2
      with:
        registry: harbor.local.winters.nz
        username: robot$github
        password: ${{ secrets.HARBOR }}
      
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    
    - name: Build and push Transmission
      uses: docker/build-push-action@v2
      with:
        context: ./DockerTransmission
        file: ./DockerTransmission/Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          harbor.local.winters.nz/public/transmission:latest
          harbor.local.winters.nz/public/transmission:${{steps.version.outputs.new_version}}

    - name: Build and push WireGuard
      uses: docker/build-push-action@v2
      with:
        context: ./DockerWireGuard
        file: ./DockerWireGuard/Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          harbor.local.winters.nz/public/wireguard-pia:latest
          harbor.local.winters.nz/public/wireguard-pia:${{steps.version.outputs.new_version}}

    - name: Build and push renamer
      uses: docker/build-push-action@v2
      with:
        context: ./rename-server
        file: ./rename-server/Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          harbor.local.winters.nz/public/rename-server:latest
          harbor.local.winters.nz/public/rename-server:${{steps.version.outputs.new_version}}

    - name: Chart version
      uses: mikefarah/yq@master
      with:
        cmd: |
          yq -i '.version = "${{steps.version.outputs.new_version}}" | .appVersion = "${{steps.version.outputs.new_version}}"' 'charts/rename-server/Chart.yaml'
          yq -i '.image.tag = "${{steps.version.outputs.new_version}}"' 'charts/rename-server/values.yaml'

    - name: Get helm dependancies
      run: |
          helm repo add k8s-at-home https://library-charts.k8s-at-home.com
          helm dependency build charts/rename-server
    
    - name: Push Helm Chart to ChartMuseum
      uses: bsord/helm-push@v4
      with:
        username: robot$github
        password: ${{ secrets.HARBOR }}
        registry-url: 'https://harbor.local.winters.nz/chartrepo/public'
        force: true
        chart-folder: charts/rename-server
