name: Create docker image
on:
  workflow_dispatch:
  repository_dispatch:
    types: [start-build]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Bump version and push tag
      id: version
      uses: hennejg/github-tag-action@v4.3.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Login to Harbor
      uses: docker/login-action@v2
      with:
        registry: harbor.local.winters.nz
        username: robot$github
        password: ${{ secrets.HARBOR }}
      
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    
    - name: Build and push Transmission
      uses: docker/build-push-action@v2
      with:
        context: ./DockerTransmission
        file: ./DockerTransmission/Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          harbor.local.winters.nz/library/transmission-mnamer:latest
          harbor.local.winters.nz/library/transmission-mnamer:${{steps.version.outputs.new_version}}

    - name: Build and push WireGuard
      uses: docker/build-push-action@v2
      with:
        context: ./DockerWireGuard
        file: ./DockerWireGuard/Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          harbor.local.winters.nz/library/wireguard-pia:latest
          harbor.local.winters.nz/library/wireguard-pia:${{steps.version.outputs.new_version}}
